version: 0.2

phases:
  build:
    commands:
      - docker build -t fe:1.3 frontend/ 

  post_build:
    commands:
      - docker login -u ${{ secrets.DOCKERHUB_USERID }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - docker tag fe:1.3 hasniawan8/fe:1.3
      - docker push hasniawan8/fe:1.3
      - docker run --name mycontainer -p 80:80 -d fe:1.3
      - docker cp mycontainer:/usr/share/nginx/html/ .
