name: s3-depl

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Backend package install and restart
        run: |
          cd backend
          pwd
          npm install
          pm2 restart index
          cd ..
          
      - name: Build React App
        run: |
          cd frontend
          npm install
          npm run build
          ls
          pwd
        
      - name: Check Directory and Path
        run: |
          pwd
          ls
        
      - name: Navigate to Frontend
        run: |
          cd frontend
          ls
          pwd
        
      - name: Deploy app build to S3 bucket
        run: |
          aws s3 sync /home/ubuntu/actions-runner/_work/React-NodeAPI-MySQL/React-NodeAPI-MySQL/frontend/dist s3://myweb.com.cm --delete
